scheme: MALNETSub
model_name: MALNETSub
distributed: false         # Set = true for multi-gpu
batch_size: 16             # For 6 GPUs: 12//6=2
num_epochs: 200
model_height: 3
node_width: 44
edge_width: 32
num_heads: 4
max_lr: 0.008
node_ffn_multiplier: 1.5
edge_ffn_multiplier: 1.5
upto_hop: 12
dataloader_workers: 4       # For multi-process data fetch
pe_random_neg: true
pe_calculated_dim : 25
pe_output_dim : 25
pe_type: magnetic_laplacian
evaluation_type : 'validation'
attn_maskout: 0.1
stop_epochs: 0
num_virtual_nodes: 0
batch_norm: True
layer_norm: False

