scheme: Perturbed_twitter5
model_name: Perturbed_twitter5
distributed: false         # Set = true for multi-gpu
batch_size: 32             # For 6 GPUs: 12//6=2
num_epochs: 200
model_height: 4
node_width: 32
edge_width: 32
num_heads: 8
max_lr: 0.008
node_ffn_multiplier: 2.0
edge_ffn_multiplier: 2.0
upto_hop: 3
dataloader_workers: 4       # For multi-process data fetch
pe_random_neg: true
pe_calculated_dim : 25
pe_output_dim : 25
pe_type: magnetic_laplacian
evaluation_type : 'validation'
attn_maskout: 0.1
stop_epochs: 0
num_virtual_nodes: 0
batch_norm: True
layer_norm: False

